# Group Assignment

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("DASH_A1.csv")
df

            Date       Close        High         Low        Open     Volume
0     24-02-2022  100.419998  100.919998   85.177002   86.879997  6639000.0
1     01-08-2024  108.199997  112.769997  105.905998  108.620003  7965400.0
2     11-02-2025  193.089996  194.000000  189.500000  190.919998  6771900.0
3     13-04-2021  149.460007  150.360001  143.550003  146.839996  2823500.0
4     17-09-2024  129.880005  131.369995  126.900002  131.350006  2825500.0
...          ...         ...         ...         ...         ...        ...
1179  27-11-2024  178.440002  180.179993  177.699997  179.990005  2031100.0
1180  12-02-2025  200.889999  201.169998  195.197998  198.000000  9989400.0
1181  01-04-2025  182.419998  183.014999  178.259995  182.050003  3740700.0
1182  25-03-2024  137.820007  138.899994  136.740005  137.050003  2162800.0
1183  26-03-2025  192.869995  199.669998  191.460007  199.240005  3848800.0

[1184 rows x 6 columns]

In [5]:
df["Date"] = pd.to_datetime(df.Date, dayfirst=True)
df.set_index("Date", inplace=True)
df

                 Close        High         Low        Open     Volume
Date
2022-02-24  100.419998  100.919998   85.177002   86.879997  6639000.0
2024-08-01  108.199997  112.769997  105.905998  108.620003  7965400.0
2025-02-11  193.089996  194.000000  189.500000  190.919998  6771900.0
2021-04-13  149.460007  150.360001  143.550003  146.839996  2823500.0
2024-09-17  129.880005  131.369995  126.900002  131.350006  2825500.0
...                ...         ...         ...         ...        ...
2024-11-27  178.440002  180.179993  177.699997  179.990005  2031100.0
2025-02-12  200.889999  201.169998  195.197998  198.000000  9989400.0
2025-04-01  182.419998  183.014999  178.259995  182.050003  3740700.0
2024-03-25  137.820007  138.899994  136.740005  137.050003  2162800.0
2025-03-26  192.869995  199.669998  191.460007  199.240005  3848800.0

[1184 rows x 5 columns]

In [6]:
df.index.is_monotonic_increasing
df.sort_index(inplace = True)
df.index.is_monotonic_increasing

True

In [7]:
df.duplicated().sum().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum().sum()

np.int64(0)

In [8]:
df.Open.fillna(df.Close.shift(1), inplace=True)

/tmp/ipykernel_18948/1145949942.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Open.fillna(df.Close.shift(1), inplace=True)

In [9]:
df.Close.ffill(inplace=True)

/tmp/ipykernel_18948/1842659904.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Close.ffill(inplace=True)

In [10]:
df["Month"] = df.index.month_name()
# since we made the date as index, so df.index is already a DatetimeIndex, which natively supports datetime properties, therefore, we do not use .dt when accessing datetime-related attributes from the index.
df

,Close,High,Low,Open,Volume,Month
Date,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,December
2020-12-10,186.000000,187.695007,172.636002,179.710007,NaN,December
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,December
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,December
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,December
...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,June
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,June
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,June
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,June
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,June

In [11]:
df['High'] = df['High'].fillna(df.groupby('Month')['High'].transform('mean'))
df['Low'] = df['Low'].fillna(df.groupby('Month')['Low'].transform('mean'))
df

,Close,High,Low,Open,Volume,Month
Date,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,December
2020-12-10,186.000000,187.695007,172.636002,179.710007,NaN,December
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,December
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,December
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,December
...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,June
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,June
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,June
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,June
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,June

In [12]:
volume_median = df['Volume'].median()

df.loc[(df['Open'] == df['Close']) & (df['Volume'].isnull()), 'Volume'] = 0

df.loc[(df['Open'] != df['Close']) & (df['Volume'].isnull()), 'Volume'] = volume_median

df

,Close,High,Low,Open,Volume,Month
Date,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,December
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506800.0,December
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,December
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,December
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,December
...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,June
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,June
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,June
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,June
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,June

In [13]:
# df.Volume = np.where(df.Close = df.Open, "green", "red")

In [14]:
# df["High"] = df.High.fillna(df.groupby("Month")["High"].mean())
# df.Low.fillna(df.Low.mean())
# df

## Firm Feature Engineering Approach

#### 1.  Simple Daily Returns:
Calculate the simple daily returns to measure the day-to-day percentage change in the Close prices.

In [16]:
df["DailyReturns"] = df.Close.pct_change()
df

,Close,High,Low,Open,Volume,Month,DailyReturns
Date,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,December,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506800.0,December,-0.018521
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,December,-0.059140
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,December,-0.085714
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,December,-0.006938
...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,June,-0.004395
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,June,-0.011587
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,June,0.013165
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,June,-0.005510
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,June,0.007017

### 2. Logarithmic Returns: 
Calculate the logarithmic returns using Close prices.

In [18]:
df["PrevClose"] = df.Close.shift() 
df["LogReturns"] = np.log(df.Close / df.PrevClose)
df

,Close,High,Low,Open,Volume,Month,DailyReturns,PrevClose,LogReturns
Date,,,,,,,,,
2020-12-09,189.509995,195.500000,163.800003,182.000000,25373700.0,December,NaN,NaN,NaN
2020-12-10,186.000000,187.695007,172.636002,179.710007,3506800.0,December,-0.018521,189.509995,-0.018695
2020-12-11,175.000000,182.000000,168.250000,176.520004,4760600.0,December,-0.059140,186.000000,-0.060961
2020-12-14,160.000000,170.000000,151.199997,169.100006,7859600.0,December,-0.085714,175.000000,-0.089612
2020-12-15,158.889999,161.419998,153.759995,157.100006,5017000.0,December,-0.006938,160.000000,-0.006962
...,...,...,...,...,...,...,...,...,...
2025-06-09,217.490005,219.830002,216.955002,218.029999,2710300.0,June,-0.004395,218.449997,-0.004404
2025-06-10,214.970001,219.210007,210.927002,216.589996,3916700.0,June,-0.011587,217.490005,-0.011654
2025-06-11,217.800003,219.529999,212.240005,214.184998,3091500.0,June,0.013165,214.970001,0.013079
2025-06-12,216.600006,219.419998,215.675003,218.080002,2510400.0,June,-0.005510,217.800003,-0.005525
2025-06-13,218.119995,218.299896,213.000000,214.190002,616326.0,June,0.007017,216.600006,0.006993

### 3. 20-Day Momentum: 
Calculate the 20-day momentum by subtracting the Close price 20 days prior from the current Close price, providing insights
into the stock's short-term trend.